### ISSUE TITLE
2.4.1 breaking facebook login example.

### ISSUE THREAD

**Issue by FrankSalad** [aws/aws-sdk-ios#385] opened 2016-05-15 00:32 UTC
The Facebook setup example mentioned [here](http://docs.aws.amazon.com/cognito/latest/developerguide/facebook.html):
```
NSString *token = [FBSDKAccessToken currentAccessToken].tokenString;
credentialsProvider.logins = @{ @(AWSCognitoLoginProviderKeyFacebook): token };
```
Appears to refer to two deprecated things: the `logins` field and `AWSCognitoLoginProviderKeyFacebook`.  As mentioned in #357 there isnt good documentation around what I need to change to make it work. 

My app is no longer able to call CognitoS3 functions, instead I get this error:
```
serialized object is neither a valid json Object nor NSData object: {
    IdentityId = "us-east-1:...";
    Logins =     {
        1 = ...string returned from [FBSDKAccessToken currentAccessToken].tokenString...
    };
}
```

**Comment by simoami** [comment] 2016-05-16 17:52
I was able to use the following signature, and it works but it gives me a deprecation message:

```swift
self.credentialsProvider = AWSCognitoCredentialsProvider(
        regionType: Constants.COGNITO_REGIONTYPE,
        identityId: nil,
        accountId: nil,
        identityPoolId: Constants.COGNITO_IDENTITY_POOL_ID,
        unauthRoleArn: Constants.COGNITO_UNAUTH_ROLE_ARN,
        authRoleArn: Constants.COGNITO_AUTH_ROLE_ARN,
        logins: logins
)
```

deprecation warning:

```log
'init(regionType:identityId:accountId:identityPoolId:unauthRoleArn:authRoleArn:logins:)' is deprecated: Use '- initWithRegionType:identityPoolId:unauthRoleArn:authRoleArn:identityProviderManager:' instead. 'identityId' and 'accountId' passed to this method will be ignored.
```

Any other signatures lead to `credentialsProvider.getIdentityId()` erroring out because the request is considered an unauthenticated request, which is not what I want.

How do I force the request to be an authenticated request and pass on a Facebook token?

I'm also not sure is supplying a custom identityProvider is a way to get around the .logins deprecation. 

Please advise.

**Comment by yosuke-matsuda** [comment] 2016-05-16 18:06
Duplicate of [this issue](https://github.com/aws/aws-sdk-ios/issues/357). Merging.

**Closed by yosuke-matsuda** 2016-05-16 18:06 UTC
