### ISSUE TITLE
Building v2.6.19 with Carthage fails

### ISSUE THREAD

**Issue by alexberlato** [aws/aws-sdk-ios#937] opened 2018-05-25 07:22 UTC
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSIoT

* In what version of SDK are you facing the problem?
2.6.19

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific iOS version?
No

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

When building the newly released version with:

carthage update --platform iOS --cache-builds

I get this error:

----------------------------
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/alex/Dev/iOS/com.worx.landroid-remote-2017/Carthage/Checkouts/aws-sdk-ios/AWSiOSSDKv2.xcodeproj -scheme AWSComprehend -configuration Release -derivedDataPath /Users/alex/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/aws-sdk-ios/2.6.19 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/17/gt39j91d44s6fgqj6rvdy2h40000gn/T/aws-sdk-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/alex/Dev/iOS/com.worx.landroid-remote-2017/Carthage/Checkouts/aws-sdk-ios)

----------------------------

The end of the attached log file reports:

----------------------------
The following build commands failed:
	CpResource AWSCoreTests/Resources/credentials.json /Users/alex/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/aws-sdk-ios/2.6.19/Build/Intermediates.noindex/ArchiveIntermediates/AWSComprehend/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSComprehendTests.xctest/credentials.json
(1 failure)
[carthage-xcodebuild.x2tcwB.log](https://github.com/aws/aws-sdk-ios/files/2038352/carthage-xcodebuild.x2tcwB.log)

----------------------------

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment] 2018-05-25 07:45
Thank you @alexberlato for reporting to us. We found the root cause of the issue. We will fix it by end of the day today. Thank you!

**Comment by steelzeh** [comment] 2018-05-25 08:18
@kvasukib Could you also supply the carthage frameworks, so we don't have to build the entire SDK, like in the other releases?

**Comment by kvasukib** [comment] 2018-05-25 18:18
Hi @steelzeh, Thank you for the feedback. I will look into it.

**Comment by kvasukib** [comment] 2018-05-25 20:40
I have uploaded the carthage frameworks here: https://github.com/aws/aws-sdk-ios/releases/tag/2.6.19

**Comment by kvasukib** [comment] 2018-05-25 22:46
I have updated the xcodeproj to fix this problem. Closing the issue. Please feel free to re-open if the issue persists.

**Closed by kvasukib** 2018-05-25 22:46 UTC
Labels: Carthage
