### ISSUE TITLE
Starting to see NetworkingError: write EPROTO in DynamoDB after upgrading to 2.4.1

### ISSUE THREAD

**Issue by helloniklas** [aws/aws-sdk-ios#371] opened 2016-05-04 11:46 UTC
So I intermittently get an error while invoking a lambda function form iOS that access dynamodb. The error is

NetworkingError: write EPROTO

I've been googling this and some seem to suggest it has to do with the TLS over http and that one has to force TLS v1? I never had this with 2.3.6 so did something change?

**Comment by yosuke-matsuda** [comment] 2016-05-04 18:10
Please post detailed steps to reproduce the issue and related logs. The thread does not include enough information for us to debug. Thanks.

**Comment by helloniklas** [comment] 2016-05-05 09:22
Invoke a lambda function through the iOS SDK. The lambda function sometimes comes back with the error NetworkingError: write EPROTO while trying to read from a dynmoDB table. This only happens occasionally. So not sure what other steps I can provide.

**Comment by yosuke-matsuda** [comment] 2016-05-05 18:16
Closing since we cannot reproduce the issue. Please feel free to update the thread when you can provide  more information.

**Closed by yosuke-matsuda** 2016-05-05 18:16 UTC
Labels: question
