### ISSUE TITLE
Issue with AWSS3TransferManagerUploadRequest

### ISSUE THREAD

**Issue by shonju** [aws/aws-sdk-ios#171] opened 2015-04-02 06:42 UTC
Every time i try to upload image it gives me error
```
Error: [Error Domain=com.amazonaws.AWSS3ErrorDomain Code=0 "The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 0.)" UserInfo=0x7f8b485367d0 {HostId=yELiNIJDsNYFDSRpGPGUy2R8B+18888qYf6/55Vxh+5C8YiTEZoyGsEFuoJy2HqX, Bucket=pt-maximaa, Endpoint=pt-maximaa.s3.amazonaws.com, Message=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., Code=PermanentRedirect, RequestId=3402C228E99811B9}]
```
Code credentialsProvider : written at "didFinishLaunchingWithOptions" method
```
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:POOL_ID];
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];
AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration; 
```
Code Upload Image:

     UIImage *img = [UIImage imageNamed:@"testimage.jpg"];
     NSString *path = [NSTemporaryDirectory() stringByAppendingPathComponent:@"image.jpg"];
     NSData *imageData = UIImageJPEGRepresentation(img, 0.5);
     [imageData writeToFile:path atomically:YES];
     NSURL *url = [[NSURL alloc] initFileURLWithPath:[NSString stringWithFormat:@"%@",path]];
     
     AWSS3TransferManager*transfermanager=[AWSS3TransferManager defaultS3TransferManager];
     AWSS3TransferManagerUploadRequest*uploadRequest=[AWSS3TransferManagerUploadRequest new];
     uploadRequest.bucket=@"mybucket";
     uploadRequest.key=@"test.jpg";
     uploadRequest.body=url;
     uploadRequest.contentLength=[NSNumber numberWithInteger:imageData.length];

    [[transfermanager upload:uploadRequest] continueWithBlock:^id(BFTask *task) {
     NSLog(@"Response : %@",task.error);
     return nil;
     }];

**Comment by yosuke-matsuda** [comment] 2015-04-02 18:50
I believe this is a duplicate of this [issue](https://forums.aws.amazon.com/thread.jspa?threadID=174855).

The error message indicates your Amazon S3 bucket is not in US Standard Region. This line sets the default service region to US East 1 (US Standard Region for S3):
```
AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];
```
You need to find out in which region your bucket is, and update the above line accordingly.

**Comment by yosuke-matsuda** [comment] 2015-04-09 22:36
Assuming the issue has been resolved. If you continue to see the issue, please feel free to update the thread with additional information. Thanks.

**Closed by yosuke-matsuda** 2015-04-09 22:36 UTC
Labels: duplicate, question
