### ISSUE TITLE
add cloudfront support

### ISSUE THREAD

**Issue by stantoncbradley** [aws/aws-sdk-ios#320] opened 2016-02-16 17:31 UTC
I have cognito + s3 configured and working.  I want to implement cloudfront to improve performance.  I don't want to generate a secure url and make a manual http request because this requires a trip to my server and is the whole reason I implemented cognito.  I think cloudfront support is a much needed feature as it streamlines this whole process.  Any advice?

Thanks!

**Comment by yosuke-matsuda** [comment] 2016-02-16 17:41
Based on your description, I assume all of your objects in the bucket are globally readable. For this use case, you can simply use Apple's native `NSURLSession` to download any objects from URLs given by Amazon CloudFront.

We are evaluating adding CloudFront support, but it will not be more than a mere wrapper of `NSURLSession`. Unless the service supports private content delivery through AWS temporary credentials, the value the SDK can provide is technically limited.

**Comment by stantoncbradley** [comment] 2016-02-16 18:09
Sorry, the bucket is not globally readable.  I have a cognito user group with permission to access the bucket.  This is why I want to use S3, since my user is already cognito authenticated.  So private content delivery is exactly what I want.  Thanks!

**Comment by yosuke-matsuda** [comment] 2016-02-16 18:11
The service currently does not support your use case. You need to generate pre-signed URLs on your server using the CloudFront certificate.

**Comment by stantoncbradley** [comment] 2016-02-16 18:16
Ok thanks.  I think this would be a valuable feature as I really like using congito and not having to make trips to my server!  Please seriously consider adding!

**Comment by ebalassanian** [comment] 2016-04-27 09:00
Throwing in my vote for this feature as well. Currently, I have to fetch signed URLs from my server for media being served up by CF.

**Comment by yosuke-matsuda** [comment] 2016-04-27 18:49
Since it is a feature request to the service team, [Amazon CloudFront Forum](https://forums.aws.amazon.com/forum.jspa?forumID=46) may be a better place to express your interests. The core of the issue is that Amazon CloudFront requires a certificate to generate a pre-signed URL. We, however, strongly discourage embedding your certificate in the mobile apps. If the service accepts AWS temporary credentials with policy variables to generate pre-signed URL, we can add support in the SDK.

Closing the issue for now. If the service adds support, we revisit this. At this moment, the beset practice is to use the server to generate the pre-signed URL. [AWS Lambda](https://aws.amazon.com/lambda/) and [Amazon API Gateway](https://aws.amazon.com/api-gateway/) can be helpful.

Thanks,

**Closed by yosuke-matsuda** 2016-04-27 18:49 UTC
Labels: feature request

**Comment by ebalassanian** [comment] 2016-04-27 18:51
Makes sense. Thanks for following up.

On Apr 27, 2016, at 11:49 AM, Yosuke Matsuda <notifications@github.com>
wrote:

Since it is a feature request to the service team, Amazon CloudFront Forum
<https://forums.aws.amazon.com/forum.jspa?forumID=46> may be a better place
to express your interests. The core of the issue is that Amazon CloudFront
requires a certificate to generate a pre-signed URL. We, however, strongly
discourage embedding your certificate in the mobile apps. If the service
accepts AWS temporary credentials with policy variables to generate
pre-signed URL, we can add support in the SDK.

Closing the issue for now. If the service adds support, we revisit this. At
this moment, the beset practice is to use the server to generate the
pre-signed URL. AWS Lambda <https://aws.amazon.com/lambda/> and Amazon API
Gateway <https://aws.amazon.com/api-gateway/> can be helpful.

Thanks,

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/aws/aws-sdk-ios/issues/320#issuecomment-215190746>
