### ISSUE TITLE
Cannot distribute app because AWSCognito not built with full bitcode

### ISSUE THREAD

**Issue by awe-mt** [aws/aws-sdk-ios#899] opened 2018-04-17 08:59 UTC
* What service are you using?
  - AWSDynamoDB
  - AWSMobileAnalytics
  - AWSCognito
  - AWSCore
  - AWSS3

* In what version of SDK are you facing the problem?

2.6.16 (latest)

* Is the issue limited to Simulators / Actual Devices?

The issue occurs when attempting to archive the app for distribution.

* Can your problem be resolved if you bump to a higher version of SDK?

Currently using latest version.

* Is this problem related to specific iOS version?

No, since this is archiving rather than building for a specific device/version.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Prebuilt framework downloaded from https://aws.amazon.com/mobile/resources/

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Archive an iMessage app with bitcode enabled, using the above mentioned frameworks. 

`
ld: bitcode bundle could not be generated because '../lib/Amazon/aws-ios-sdk-2.6.16/frameworks/AWSCognito.framework/AWSCognito' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file 
`

**Comment by awe-mt** [comment] 2018-04-17 09:28
Looks like this is a duplicate of #814.

**Comment by cbommas** [comment] 2018-04-20 00:53
hello @awe-mt 

We have fixed this issue and the updated libraries will be available in our next release.

**Comment by Wilsonilo** [comment] 2018-04-26 16:52
I can confirm, trying to release got "ld: bitcode bundle could not be generated because './AWSCore.framework/AWSCore' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file './AWSCore.framework/AWSCore' for architecture arm64"

Turning bitcode off was only solution to bypass

**Comment by kvasukib** [comment] 2018-05-01 18:33
We have fixed it in 2.6.17. Please upgrade and let us know the feedback. Closing the issue.

**Closed by kvasukib** 2018-05-01 18:33 UTC

**Comment by Wilsonilo** [comment] 2018-05-03 14:58
Bitcode seems to be fixed now doing my archive.
