### ISSUE TITLE
AWSS3TransferManagerDownloadRequest fails when key contains plus sign.

### ISSUE THREAD

**Issue by thebugcode** [aws/aws-sdk-ios#442] opened 2016-08-10 13:35 UTC
I have a s3 download request which fails for a specific image with a very specific name:

`let request = AWSS3TransferManagerDownloadRequest()`
 `request.key = "17d7927c-5c5a-4c02-a852-63aa5496ba00/Nordic+Kids%27+5+Piece+Table+and+Stool+Set.jpg"
`

I have this image in my s3 bucket and we can download it using the command line. Unfortunately using aws-sdk-ios download fails. I suspect it is because the plus sign is being encoded and the final request looks more like this:
"17d7927c-5c5a-4c02-a852-63aa5496ba00/Nordic%2BKids%27%2B5%2BPiece%2BTable%2Band%2BStool%2BSet.jpg"

Any ideas?

**Comment by mlshon** [comment] 2016-08-10 22:38
What is the failure message that you're getting?

Can you provide steps to reproduce this?  We are unable to reproduce this error on our side.

**Comment by thebugcode** [comment] 2016-08-11 10:58
I am getting this error:
`AWS download error: Error Domain=com.amazonaws.AWSServiceErrorDomain Code=11 "(null)" UserInfo={HostId=eKORPj3voxE3WX1TyUB4tGGWjxBk9JSAdWHZe5K4EUWMNGxNm3RayWlcNZN9ozCuKCfthC6gFvA=, Message=Access Denied, Code=AccessDenied, RequestId=7ADC7C1C730B91BE}`

**Comment by thebugcode** [comment] 2016-08-11 12:01
I now have more info. It seems that the apostrophe symbol (%27) is causing the issue. 
The image is stored in my bucket under the exact following name: `Nordic+Kids%27+5+Piece+Table+and+Stool+Set.jpg`
If I change it's name to `Nordic+Kids+5+Piece+Table+and+Stool+Set.jpg` I can download it with no problems.


Every aws sdk library(.NET, CLI) can access this resource except the iOS one. My best guess is that because i set the request key value to be `Nordic+Kids%27+5+Piece+Table+and+Stool+Set.jpg` then when the request is received by s3 servers this is actually decoded into `Nordic+Kids'+5+Piece+Table+and+Stool+Set.jpg` and this is not the name under which the image is stored in my bucket. In my bucket as I explained it is stored as `Nordic+Kids%27+5+Piece+Table+and+Stool+Set.jpg`

**Comment by karthiksaligrama** [comment] 2016-08-11 15:56
thanks that helps. We will get back to you when we have a fix.

**Comment by mlshon** [comment] 2017-01-12 19:39
The fix for this is available in the new version of the SDK.

**Closed by mlshon** 2017-01-12 19:39 UTC
Labels: bug
