### ISSUE TITLE
AWSCognitoIdentity getId sends wrong body

### ISSUE THREAD

**Issue by pwrprogrammer** [aws/aws-sdk-ios#439] opened 2016-08-06 23:02 UTC
When calling the `getId` function on an `AWSCognitoIdentity` object, the body which is sent does not contain all specified parameters.

## Code example

    AWSCognitoIdentityGetIdInput *input = [AWSCognitoIdentityGetIdInput new];
    input.accountId      = @"...";
    input.logins         = @{AWSIdentityProviderFacebook: @"..."};
    input.identityPoolId = @"...";
    
    [[[AWSCognitoIdentity defaultCognitoIdentity] getId:input] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityGetCredentialsForIdentityResponse *> * _Nonnull t)
     {
         NSLog(@"%@", t1);
         return nil;
     }];

### Request headers

    {
      "Content-Type" = "application/x-amz-json-1.1";
      Host = "cognito-identity.eu-west-1.amazonaws.com";
      "User-Agent" = "aws-sdk-iOS/2.4.6 iPhone-OS/9.3.3 de_AT";
      "X-Amz-Date" = 20160806T223906Z;
      "X-Amz-Target" = "AWSCognitoIdentityService.GetId";
    }

### Request body

    {"IdentityPoolId":"eu-west-1:<REDACTED>"}

Obviously, the account id and the logins dictionary are missing.
Surely, the request gets rejected by the AWS API endpoint:

### Response headers

    {
      Connection = "keep-alive";
      "Content-Length" = 111;
      "Content-Type" = "application/x-amz-json-1.1";
      Date = "Sat, 06 Aug 2016 22:39:06 GMT";
      "x-amzn-ErrorMessage" = "Unauthenticated access is not supported for this identity pool.";
      "x-amzn-ErrorType" = "NotAuthorizedException:";
      "x-amzn-RequestId" = "...";
    }

### Response body

    {"__type":"NotAuthorizedException","message":"Unauthenticated access is not supported for this identity pool."}

## Other tests

I also tried to rebuild the request with an API client.
When calling the AWS API like this:

    curl -X "POST" "https://cognito-identity.eu-west-1.amazonaws.com/" \
	-H "X-Amz-Target: AWSCognitoIdentityService.GetId" \
	-H "Content-Type: application/x-amz-json-1.1" \
	-d "{\"IdentityPoolId\":\"...\",\"AccountId\":\"...\",\"Logins\":{\"graph.facebook.com\":\"...\"}}"

everything works fine. I get a 200 response code and the identity id.
When I rebuild the body like in the console output, I also get a 400 response code and a `NotAuthorizedException` error.

**Comment by wdane** [comment] 2016-08-09 18:17
The error response message means that you have not enabled unauthenticated access for this identity pool. Without unauthenticated access, you would need to authenticate with Cognito User Pools, or Developer Authentication, or a supported third party like Facebook or Google.

What credentials are you using for the API Client request?

**Comment by karthiksaligrama** [comment] 2016-08-12 16:03
i'm not able to reproduce this error? I followed the same steps you did and it does send the logins information over the wire.

**Comment by karthiksaligrama** [comment] 2016-09-20 06:25
assuming resolved. Closing this issue. Please open a new one if the issue continues to persist.

**Closed by karthiksaligrama** 2016-09-20 06:25 UTC
Labels: question
