### ISSUE TITLE
The `logins` dictionary deprecation and suggested workaround

### ISSUE THREAD

**Issue by simoami** [aws/aws-sdk-ios#386] opened 2016-05-16 18:49 UTC
From the changelog

```
* **(Breaking)** Updated the credentials provider and identity provider protocols to asynchronous interfaces instead of previous synchronous ones. The `logins` dictionary of `AWSCognitoCredentialsProvider` is now deprecated. Use `AWSIdentityProviderManager` to provide login providers' credentials. See `AWSCredentialsProvider.h` and `AWSIdentityProvider.h` for more details.
```

Can you provide a small example (preferably in swift) on how to "Use `AWSIdentityProviderManager` to provide login providers' credentials" as the notes describe?

**Comment by yosuke-matsuda** [comment] 2016-05-16 19:25
Duplicate of [this issue](https://github.com/aws/aws-sdk-ios/issues/357). Merging.

**Closed by yosuke-matsuda** 2016-05-16 19:25 UTC
