### ISSUE TITLE
2-3 seconds delay before downloading files

### ISSUE THREAD

**Issue by ataranlen** [aws/aws-sdk-ios#206] opened 2015-06-24 13:42 UTC
I first experienced this issue when using AWSS3TransferManager and AWSExecutor, and wanted to see if Presigned URL's had the same issue, so I'm using the S3BackgroundTransferSampleObjC and trying to debug an issue with downloading files.

1. Launch the sample
2. Upload the text file (set to 10 lines instead of 20000, file already exists on S3, so I skip this step most tests.)
3. Download the same text file:
4. Watch as the sample takes ~2 seconds before AWS responds with the 18 Byte file.

```
2015-06-24 08:32:51.239 S3BackgroundTransferSampleObjC[3838:1089921] Started Download (Button clicked now)
2015-06-24 08:32:51.251 S3BackgroundTransferSampleObjC[3838:1089921] Warning: A long-running operation is being executed on the main thread. 
 Break on warnBlockingOperationOnMainThread() to debug.
2015-06-24 08:32:52.007 S3BackgroundTransferSampleObjC[3838:1089921] download presignedURL is: *snip*
2015-06-24 08:32:53.024 S3BackgroundTransferSampleObjC[3838:1089940] DownloadTask progress: 1.000000
2015-06-24 08:32:53.026 S3BackgroundTransferSampleObjC[3838:1089948] -[SecondViewController URLSession:downloadTask:didFinishDownloadingToURL:]
2015-06-24 08:32:53.035 S3BackgroundTransferSampleObjC[3838:1089948] S3 DownloadTask: <__NSCFBackgroundDownloadTask: 0x157d1c900>{ taskIdentifier: 1 } completed successfully
```

I've done testing on our Fiber Optic line, 4G, 3G, etc, and seem to get similar results on each.

How should I go about debugging this?

**Comment by ataranlen** [comment] 2015-06-24 14:06
Just for clarification, I wrapped the *Background* sample code onto a background thread to remove the Main thread warning, got similar results.

```
2015-06-24 09:04:37.924 S3BackgroundTransferSampleObjC[3856:1093880] Started Download
2015-06-24 09:04:38.553 S3BackgroundTransferSampleObjC[3856:1093899] download presignedURL is: *snip*
2015-06-24 09:04:39.354 S3BackgroundTransferSampleObjC[3856:1093900] DownloadTask progress: 1.000000
2015-06-24 09:04:39.360 S3BackgroundTransferSampleObjC[3856:1093900] -[SecondViewController URLSession:downloadTask:didFinishDownloadingToURL:]
2015-06-24 09:04:39.369 S3BackgroundTransferSampleObjC[3856:1093900] S3 DownloadTask: <__NSCFBackgroundDownloadTask: 0x13d62d5a0>{ taskIdentifier: 1 } completed successfully
```

**Comment by yosuke-matsuda** [comment] 2015-06-24 21:46
It may be beneficial to see what data is transferred since you are not debugging the AWS SDK but the iOS's HTTP client's behavior. There are a few HTTP sniffers available; you may want to try one of these.

In general, it sometimes takes a few seconds for the OS to wake up and establish the Internet connection before you can start transferring data if the connection pool is empty. It could be just an expected behavior.

**Comment by ataranlen** [comment] 2015-06-24 23:12
In our case, we just did a single REST call right before making the call(s) to the AWS server. I know that the connection is working.

**Closed** 2015-07-06 23:54 UTC
Labels: question

**Comment by vickyrappier** [comment] 2015-09-11 04:36
I face the same issue , exactly mentioned by Ataranlen, also the warning doesn't go for the long running task, due to this in my chat application this file is skipped to upload and sending over my chat is missed. So If i am doing 10 files upload every time the failure chance is 10% .
