### ISSUE TITLE
AWSS3TransferUtility should return an error when specifying wrong region.

### ISSUE THREAD

**Issue by nRewik** [aws/aws-sdk-ios#305] opened 2016-01-18 08:07 UTC
I have my bucket located at Singapore. And I've set the configuration to the wrong region by mistake.

Then, I use `AWSS3TransferUtility` to upload binary data to the bucket. 

Everything went good. There's no error. However, I go check the file in S3 console. There's nothing there. 

I'm very confused since my output said "Successfully Upload". No error is produced from completion block. I also track the upload progress, and it run as usual 0 to 100%.

After 2-3 hrs, I found it. So I change the region to `.APSoutheast1`. Now it works.

So, I think AWS should produce a wrong region error or something. It should be very useful.

**Comment by rohandubal** [comment] 2016-01-21 01:55
Hi nRewik, thanks for reporting this. I will have a look into this.

**Comment by yosuke-matsuda** [comment] 2016-01-25 19:22
This seems to be a duplicate of [this issue](https://github.com/aws/aws-sdk-ios/issues/281). Merging this thread into the original one.

**Closed by yosuke-matsuda** 2016-01-25 19:22 UTC
