### ISSUE TITLE
LOG Macros errors with XMPPFramework

### ISSUE THREAD

**Issue by vikram17000** [aws/aws-sdk-ios#664] opened 2017-05-08 15:38 UTC
Hi - this relates to the issue #655 - the same was closed but unfortunately, the errors and warnings still persist when integrating the latest release (2.5.6) in a project that already has XMPPFramework. Below are some of the warnings / errors generated.

I'm relying on integrating the AWS iOS SDK via frameworks, hence I'd really appreciate if the latest release can fix these issues so that I can grab the released frameworks to integrate. If I try to fix the AWS SDK source (by not defining these macros) and then build, unfortunately the errors persist (ditto if I fix the XMPP code too). In fact, I'm a tad concerned about building the frameworks myself since doing so does not generate 5 frameworks (eg Polly, Log, KMS, etc.), hence would rather rely on leveraging the AWS release directly.

Many thanks for your help indeed - I currently have the 2.4.7 release frameworks which integrate fine - would want to upgrade to the latest now...

**Warnings / errors:**

```
LOG_MACRO macro redefined (DDLog.h)
LOG_MAYBE macro redefined (DDLog.h)
THIS_FILE macro redefined (DDLog.h)

Ambiguous expansion of macro LOG_MAYBE
Ambiguous expansion of macro THIS_FILE
Ambiguous expansion of macro LOG_MACRO


XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:76:17: Implicit conversion of an Objective-C pointer to 'const char * _Nonnull' is disallowed with ARC
XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:76:4: Implicit conversion of a non-Objective-C pointer type 'const char *' to 'id _Nullable' is disallowed with ARC
XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:273:18: Implicit conversion of an Objective-C pointer to 'const char * _Nonnull' is disallowed with ARC
XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:273:3: Implicit conversion of a non-Objective-C pointer type 'const char *' to 'id _Nullable' is disallowed with ARC

XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:76:17: Incompatible pointer types sending 'NSString *' to parameter of type 'const char * _Nonnull'
XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:76:4: Incompatible pointer types sending 'const char *' to parameter of type 'id _Nullable'
XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:273:18: Incompatible pointer types sending 'NSString *' to parameter of type 'const char * _Nonnull'
XMPPFramework/Core/Extensions/XEP-0054/XMPPvCardTempModule.m:273:3: Incompatible pointer types sending 'const char *' to parameter of type 'id _Nullable'
```

**Comment by rohandubal** [comment] 2017-05-08 22:48
Hello @vikram17000 

To help better could you provide us with a sample project where we can reproduce this? I am unable to reproduce this on my end. You could send me a link to that project where I can download it or create a repo on Github which I can clone. I do not require any implementation details in that project but only the frameworks and the imports so that I can reproduce the warnings  / errors.

Thanks,
Rohan

**Comment by vikram17000** [comment] 2017-05-09 03:17
Sure thanks @rohandubal  ... let me try get that out for you over the next couple of days!

**Comment by vickydhas** [comment] 2017-05-09 07:53
The issue still exist : Please check as the AWSCocoaLumberJack is conflicting with the traditional CocoaLunberJack logger and having multiple project warnings.

![screen shot 2017-05-09 at 3 51 57 pm](https://cloud.githubusercontent.com/assets/834663/25840743/aa518082-34cf-11e7-91a5-da01f9adbb7a.png)

**Comment by ppoletti** [comment] 2017-05-09 13:05
I am seeing a similar issue with conflicting LOG_MAYBE definitions. One is the definition defined in CocoaLumberJack in the DDLogMacros.h file that is used by many of our internal pods and the other is in AWSDDLogMacros.h which is in the AWSCore pod. It looks like this file is copied and pasted with a prefix on the front off many of the higher level macros but as you dig deeper you can see on line 75 of AWSDDLogMacros.h which does not have a AWS specific prefix or suffix.

#define LOG_MAYBE(async, lvl, flg, ctx, tag, fnct, frmt, ...) 
do { LOG_MACRO(async, lvl, flg, ctx, tag, fnct, frmt, ##VA_ARGS); } while(0)

This conflicts with at least in my version the same named define of the following.

#define LOG_MAYBE(async, lvl, flg, ctx, tag, fnct, frmt, ...) 
do { if(lvl & flg) LOG_MACRO(async, lvl, flg, ctx, tag, fnct, frmt, ##VA_ARGS); } while(0)

on line 82 of my version of CocoaLumberJack within the DDLogMacros.h file. We are not using Carthage and only pods in our configuration.

**Comment by harrisnb** [comment] 2017-05-12 15:32
Same here there is a conflict between CocoaLumberJack and AWS Core.

Defining the same macro names creates ambiguous macros >ppoletti has summed up the issue as we are seeing it in our project.

The conflict appears to be for LOG_MACRO, LOG_MAYBE and LOG_ASYNC_ENABLED

**Comment by rohandubal** [comment] 2017-05-18 01:54
Fixed with 2.5.7.

**Closed by rohandubal** 2017-05-18 01:54 UTC

**Comment by vickydhas** [comment] 2017-05-19 07:18
Issue exist for the THE_FILE, THE_METHOD MACROS

....Filename.m.m:333: DDLogDebug(@"socketDidConnect %@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:340: DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:395: DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:456: DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:461: DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:473: DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:482: DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:521: DDLogDebug(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:1125: DDLogVerbose(@"%@: %@ - %@", THIS_FILE, THIS_METHOD, [presence fromStr]);
....Filename.m.m:1170: DDLogVerbose(@"%@: %@", THIS_FILE, THIS_METHOD);
....Filename.m.m:1270: DDLogDebug(@"%@: %@ : %@", THIS_FILE, THIS_METHOD,enabled);
....Filename.m.m:1277: DDLogDebug(@"%@: %@ : %@", THIS_FILE, THIS_METHOD,stanzaIds);
....Filename.m.m:1299: DDLogDebug(@"%@: %@ : %@", THIS_FILE, THIS_METHOD,failed);
....Filename.m.m:1307: DDLogDebug(@"%@: %@ : %u", THIS_FILE, THIS_METHOD,connectionFlags);

screen shot 2017-05-19 at 2 32 41 pm

**Comment by vikram17000** [comment] 2017-06-05 23:04
True - the issue still exists...
