### ISSUE TITLE
Uploading a raw JSON file results in empty Content-Encoding header

### ISSUE THREAD

**Issue by yorkepb** [aws/aws-sdk-ios#443] opened 2016-08-10 22:49 UTC
When I using the SDK to upload a raw JSON file, I am specifying all the details correctly, or so I think... But perhaps I am doing something wrong here. 

For content-type I have is `application/json`
for content-encoding I leave the property `nil`
When I perform the upload I noticed that the content-encoding header is `aws-chunked`
Upon completing the transfer, if I inspect the file, it has a content-encoding header but the value is an empty string. Any idea why an empty string is being used for this header and how to stop it?

**Comment by karthiksaligrama** [comment] 2016-08-15 20:31
Can you give me more details on service, version of sdk, steps to reproduce.

**Comment by yorkepb** [comment] 2016-08-15 20:47
Hello, sorry for the lack of appropriate details, please let me know if you need anymore information:

The service is S3, the SDK version is 2, Steps to reproduce:

I have an iOS app which does the following:

* I setup the service manager using USEast1 and the appropriate credentials
* I get an S3 transfer manager using the default manager singleton `[AWSS3TransferManager defaultS3TransferManager];`
* I create a new upload request with a bucket, key, body, contentType, cacheControl, ACL
* I call: `[[transferManager upload:uploadRequest] continueWithBlock:^id _Nullable(AWSTask * _Nonnull task) { }];` to upload the request.

When doing it, I checked the contentEncoding and it is nil. During the process it gets changed to `aws-chunked` (this is in the SDK). Then after the transfer has completed, upon inspecting the file on S3, I see the file has a `content-encoding` header with an empty value.

**Comment by karthiksaligrama** [comment] 2016-08-15 20:51
thanks that helps. Let me investigate this and get back to you

**Comment by yorkepb** [comment] 2016-08-15 20:51
thank you so much!

**Comment by Sunbir** [comment] 2017-11-07 05:54
I'm experiencing this bug as well. It is really bad in the sense that having an empty content encoding header breaks cloudfront gzip compression of the object -- and the header metadata for the object is immutable/un-repairable...

**Comment by dimaborenko** [comment] 2018-05-16 21:16
I'm having the exact same issue using the latest version of SDK. The issue is pretty critical, since it breaks Lambda Edge function on CloudFront. Lambda function fails every time CDN serves a file with Content-Encoding header set to an empty string.

This is definitely a bug in the SDK, which really needs to be fixed. Should I file a new issue, since this was automatically closed? Please advise.

Btw, there was a similar issue in .NET SDK aws/aws-sdk-net#559, which was fixed with aws/aws-sdk-net@1869c85b4a28b90342170efa7f2ec8afc9661a21.

**Comment by yorkepb** [comment] 2018-05-16 21:57
did anything ever come of the investigation originally mentioned by @karthiksaligrama?

**Comment by kvasukib** [comment] 2018-05-16 22:28
Hi @yorkepb, just to summarize the problem and correct my understanding:

"Using the AWSS3TransferManager and try to upload a file to S3, when content-encoding is set to nil, the SDK changes it to aws-chunked but on the S3 console, the content-encoding is empty"

Am I correct here? Can you share a code snippet if possible?

FYI, we introduced support for multi-part uploads in AWSS3TransferUtility and that will be our preferred path going forward for S3. I will try to reproduce the problem with TransferManager and TransferUtility.

**Comment by dimaborenko** [comment] 2018-05-16 23:40
Hi @kvasukib, I'm sharing my code in the meantime:

```
[AWSS3TransferManager registerS3TransferManagerWithConfiguration:configuration forKey:transferManagerKey];
AWSS3TransferManager * transferManager = [AWSS3TransferManager S3TransferManagerForKey:transferManagerKey];

AWSS3TransferManagerUploadRequest * uploadRequest = [AWSS3TransferManagerUploadRequest new];
uploadRequest.bucket = bucketName;
uploadRequest.key = key;
uploadRequest.body = playlistFileURL;
uploadRequest.ACL = AWSS3ObjectCannedACLPublicRead;
uploadRequest.contentType  = @"application/x-mpegURL";
uploadRequest.contentLength = @(playlistData.length);

[[transferManager upload:uploadRequest] continueWithBlock:^id _Nullable(AWSTask * _Nonnull task)
 {
     ...
     
     return nil;
 }];
```

That's what I see in AWS S3 console after uploading is done:

<img width="500" alt="screenshot 2018-05-16 19 18 06" src="https://user-images.githubusercontent.com/39347024/40149134-ea79aa32-593f-11e8-84f0-a227c5d67d87.png">

Please let me know if there are any other useful details I can provide.

**Comment by dimaborenko** [comment] 2018-05-25 00:19
Hi @kvasukib, just checking in to see if there are any updates on this issue.

**Comment by cbommas** [comment] 2018-07-10 21:39
@dimaborenko 
Apologies for the delay in the response here. We have made numerous improvements to the `AWSS3TransferUtility` over the past few releases and are positioning that as the recommended path forward for transfers with S3. The `AWSS3TransferManager` is in the process of being deprecated.

I would recommend that you use the TransferUtility in your code base. I would be happy to help you if you have any questions or concerns on migrating to the TransferUtility.

**Comment by cbommas** [comment] 2018-07-25 19:49
@dimaborenko 

Closing this as I haven't seen a response. Please feel free to re-open if you have questions.

**Closed by cbommas** 2018-07-25 19:49 UTC
Labels: Core, S3, requesting feedback
