### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by bbilonog** [aws/aws-sdk-ios#315] opened 2016-02-11 09:34 UTC
Good morning, or afternoon, or evening, depending on where you are :]

Please add Carthage package manager support. https://github.com/Carthage/Carthage

**Comment by yosuke-matsuda** [comment] 2016-02-11 19:37
This is a duplicate of [this issue](https://github.com/aws/aws-sdk-ios/issues/184). Merging.

**Closed by yosuke-matsuda** 2016-02-11 19:37 UTC
