### ISSUE TITLE
Crash in AWSKinesisRecorder 

### ISSUE THREAD

**Issue by taher-mosbah** [aws/aws-sdk-ios#293] opened 2015-12-13 14:33 UTC
I have the following crash in fabric.io (4 times) , I don't think it's caused by my code but related to fmdb :

`````
Thread : Crashed: fmdb.<AWSFMDatabaseQueue: 0x129048820>
0  app_name           0x100230348 __38-[AWSKinesisRecorder submitAllRecords]_block_invoke_3 (AWSKinesisRecorder.m:320)
1  app_name           0x10021246c __42-[AWSTask continueWithExecutor:withBlock:]_block_invoke_2 (AWSTask.m:305)
2  app_name           0x1001d7020 __30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:45)
3  app_name           0x1001d7580 -[AWSExecutor execute:] (AWSExecutor.m:109)
4  app_name           0x100212424 __42-[AWSTask continueWithExecutor:withBlock:]_block_invoke (AWSTask.m:302)
5  app_name           0x1002122b0 -[AWSTask continueWithExecutor:withBlock:] (AWSTask.m:337)
6  app_name           0x1002128d0 -[AWSTask continueWithExecutor:withSuccessBlock:] (AWSTask.m:349)
7  app_name           0x100212a08 -[AWSTask continueWithSuccessBlock:] (AWSTask.m:359)
8  app_name           0x10022fff8 __38-[AWSKinesisRecorder submitAllRecords]_block_invoke_2 (AWSKinesisRecorder.m:320)
9  app_name           0x1001ddca4 __49-[AWSFMDatabaseQueue beginTransaction:withBlock:]_block_invoke (AWSFMDatabaseQueue.m:182)
10 libdispatch.dylib              0x199899770 _dispatch_client_callout + 16
11 libdispatch.dylib              0x1998a49c4 _dispatch_barrier_sync_f_invoke + 100
12 app_name           0x1001ddbe4 -[AWSFMDatabaseQueue beginTransaction:withBlock:] (AWSFMDatabaseQueue.m:171)
13 app_name           0x10022f864 __38-[AWSKinesisRecorder submitAllRecords]_block_invoke (AWSKinesisRecorder.m:260)
14 app_name           0x10021296c __49-[AWSTask continueWithExecutor:withSuccessBlock:]_block_invoke (AWSTask.m:353)
15 app_name           0x10021246c __42-[AWSTask continueWithExecutor:withBlock:]_block_invoke_2 (AWSTask.m:305)
16 app_name           0x1001d7020 __30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:45)
17 app_name           0x1001d7580 -[AWSExecutor execute:] (AWSExecutor.m:109)
18 app_name           0x100212424 __42-[AWSTask continueWithExecutor:withBlock:]_block_invoke (AWSTask.m:302)
19 app_name           0x1002122b0 -[AWSTask continueWithExecutor:withBlock:] (AWSTask.m:337)
20 app_name           0x1002128d0 -[AWSTask continueWithExecutor:withSuccessBlock:] (AWSTask.m:349)
21 app_name           0x100212a08 -[AWSTask continueWithSuccessBlock:] (AWSTask.m:359)
22 app_name           0x10022f730 -[AWSKinesisRecorder submitAllRecords] (AWSKinesisRecorder.m:256)
23 app_name           0x10021296c __49-[AWSTask continueWithExecutor:withSuccessBlock:]_block_invoke (AWSTask.m:353)
24 app_name           0x10021246c __42-[AWSTask continueWithExecutor:withBlock:]_block_invoke_2 (AWSTask.m:305)
25 app_name           0x1001d7020 __30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:45)
26 app_name           0x1001d7580 -[AWSExecutor execute:] (AWSExecutor.m:109)
27 app_name           0x100212424 __42-[AWSTask continueWithExecutor:withBlock:]_block_invoke (AWSTask.m:302)
28 app_name           0x1002122b0 -[AWSTask continueWithExecutor:withBlock:] (AWSTask.m:337)
29 app_name           0x1002128d0 -[AWSTask continueWithExecutor:withSuccessBlock:] (AWSTask.m:349)
30 app_name           0x100212a08 -[AWSTask continueWithSuccessBlock:] (AWSTask.m:359)
31 app_name           0x1001210f0 -[WSManager sendEventToP4DWithType:value:context:andCompletion:] (WSManager.m:1172)
32 app_name           0x1000d0238 -[WeatherRootViewController viewDidLoad] (WeatherRootViewController.m:54)
33 UIKit                          0x1899ff610 -[UIViewController loadViewIfRequired] + 1124
34 UIKit                          0x189a176ec -[UIViewController __viewWillAppear:] + 132
35 UIKit                          0x189babd68 -[UINavigationController _startCustomTransition:] + 1044
36 UIKit                          0x189abb430 -[UINavigationController _startDeferredTransitionIfNeeded:] + 688
37 UIKit                          0x189abb10c -[UINavigationController __viewWillLayoutSubviews] + 60
38 UIKit                          0x189abb074 -[UILayoutContainerView layoutSubviews] + 208
39 UIKit                          0x1899faff0 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 644
40 QuartzCore                     0x189201f14 -[CALayer layoutSublayers] + 148
41 QuartzCore                     0x1891fcb20 CA::Layer::layout_if_needed(CA::Transaction*) + 292
42 QuartzCore                     0x1891fc9e0 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
43 QuartzCore                     0x1891fc07c CA::Context::commit_transaction(CA::Transaction*) + 252
44 QuartzCore                     0x1891fbdd0 CA::Transaction::commit() + 516
45 QuartzCore                     0x1891f54bc CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80
46 CoreFoundation                 0x18445fc30 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
47 CoreFoundation                 0x18445d9d4 __CFRunLoopDoObservers + 372
48 CoreFoundation                 0x18438cde0 CFRunLoopRunSpecific + 416
49 GraphicsServices               0x18f4e0088 GSEventRunModal + 180
50 UIKit                          0x189a66f44 UIApplicationMain + 204
51 app_name           0x1000d73d0 main (main.m:14)
52 libdyld.dylib                  0x1998ca8b8 start + 4
`````

**Comment by rohandubal** [comment] 2015-12-14 18:55
Hi, thanks for reporting this. Could you please provide with some sample code or steps to reproduce this? Thanks.

-Rohan

**Comment by taher-mosbah** [comment] 2015-12-14 19:35
Hi, thank you for your answer, the crash was reported in fabric (crashlytics) and I didn't see it in debug.

**Comment by yosuke-matsuda** [comment] 2015-12-16 19:34
At this moment, we are closing the issue since we cannot reproduce the issue. However, if you find a way to reproduce it, please feel free to update the thread. Thank you.

**Closed** 2015-12-29 20:29 UTC
Labels: question
