### ISSUE TITLE
Error installing SDK with Cocoapods

### ISSUE THREAD

**Issue by tomermobli** [aws/aws-sdk-ios#136] opened 2015-01-20 15:58 UTC
I get this error when installing the sdk with cocoapods after 'pod install':

    - `Mantle (~> 1.5.4)` required by `Podfile`
    - `Mantle (~> 1.4.1)` required by `AWSiOSSDKv2 (2.0.0)`
    - `AWSiOSSDKv2` required by `Podfile`

Please add a new tag and a new pod spec with a more modern Mantle version

Thanks

**Comment by yosuke-matsuda** [comment] 2015-01-20 19:12
Duplicate of [this issue](https://github.com/aws/aws-sdk-ios/issues/113).

**Closed by yosuke-matsuda** 2015-01-20 19:12 UTC
